version: '3'
services:
  broker:
    build:
      context: ./broker
    networks:
      - my-network
    hostname: broker-container

  subscriber:
    build:
      context: ./subscriber
    networks:
      - my-network
    hostname: subscriber-container

  publisher:
    build:
      context: ./publisher
    networks:
      - my-network
    hostname: publisher-container

networks:
  my-network:
